# Generated by Django 5.0.6 on 2024-07-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('lista_produtos', models.JSONField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tipo', models.CharField(choices=[('', 'Selecione'), ('B', 'Bebida'), ('C', 'Comida')], default='', max_length=1)),
                ('data_cadastro', models.DateTimeField()),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
