# Generated by Django 5.0.6 on 2024-07-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='lista_produtos',
            field=models.TextField(),
        ),
    ]
