# Generated by Django 5.0.6 on 2024-07-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_pedido_lista_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='cardapio.produto'),
        ),
    ]
